apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    application: elasticsearch
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
spec:
  replicas: 1
  selector:
    matchLabels:
      application: elasticsearch
  template:
    metadata:
      labels:
        application: elasticsearch
      annotations:
        co.elastic.monitor/0.type: icmp
        co.elastic.monitor/0.hosts: ${data.host}
        co.elastic.monitor/0.schedule: "@every 5s"
        co.elastic.monitor/0.name: ${data.kubernetes.pod.name}
        co.elastic.monitor/0.tags.0: elasticsearch
        co.elastic.monitor/0.tags.1: development
        co.elastic.monitor/0.tags.2: pod
        co.elastic.monitor/1.type: tcp
        co.elastic.monitor/1.hosts: ${data.host}:9200
        co.elastic.monitor/1.schedule: "@every 5s"
        co.elastic.monitor/1.name: ${data.kubernetes.pod.name}
        co.elastic.monitor/1.tags.0: elasticsearch
        co.elastic.monitor/1.tags.1: development
        co.elastic.monitor/1.tags.2: pod
        co.elastic.monitor/2.type: http
        co.elastic.monitor/2.hosts: ${data.host}:9200/_cluster/health
        co.elastic.monitor/2.schedule: "@every 5s"
        co.elastic.monitor/2.name: ${data.kubernetes.pod.name}
        co.elastic.monitor/2.tags.0: elasticsearch
        co.elastic.monitor/2.tags.1: development
        co.elastic.monitor/2.tags.2: pod
    spec:
      terminationGracePeriodSeconds: 300
      # securityContext:
      #   privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
          - name: discovery.type
            value: "single-node"
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: standard
      # NOTE: You can increase the storage size
      resources:
        requests:
          storage: 500Gi
