apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-config
  namespace: monitoring
  labels:
    application: heartbeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
data:
  heartbeat.yml: |-
    heartbeat.autodiscover:
     # Autodiscover pods
     providers:
       - type: kubernetes
         resource: pod
         scope: cluster
         hints.enabled: true
    
     # Autodiscover services
       - type: kubernetes
         resource: service
         scope: cluster
         hints.enabled: true

     # Autodiscover nodes
       - type: kubernetes
         resource: node
         node: ${NODE_NAME}
         scope: cluster
         templates:
           - condition: ~
             config:
               - hosts:
                   - ${data.host}
                 name: ${data.kubernetes.node.name}
                 schedule: '@every 10s'
                 timeout: 5s
                 type: icmp

    processors:
      - add_kubernetes_metadata: ~

    output.elasticsearch:
      hosts: ['${ELASTIC_CUSTOM_HOST:elasticsearch}:${ELASTIC_CUSTOM_PORT:9200}']
      username: ${ELASTIC_CUSTOM_USERNAME:elastic}
      # password: ${ELASTIC_PASSWORD}