---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heartbeat
  labels:
    application: heartbeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
subjects:
- kind: ServiceAccount
  name: heartbeat
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: heartbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heartbeat
  namespace: monitoring
  labels:
    application: heartbeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
subjects:
  - kind: ServiceAccount
    name: heartbeat
    namespace: monitoring
roleRef:
  kind: Role
  name: heartbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heartbeat-kubeadm-config
  namespace: monitoring
  labels:
    application: heartbeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
subjects:
  - kind: ServiceAccount
    name: heartbeat
    namespace: monitoring
roleRef:
  kind: Role
  name: heartbeat-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heartbeat
  labels:
    application: heartbeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - pods
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - replicasets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: heartbeat
  # should be the namespace where heartbeat is running
  namespace: monitoring
  labels:
    application: heartbeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: heartbeat-kubeadm-config
  namespace: monitoring
  labels:
    application: heartbeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heartbeat
  namespace: monitoring
  labels:
    application: heartbeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity