
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: agnhost
  labels:
    application: agnhost
    version: "2.39"
    release: "r7"
    stage: development
    component: example-apps
    part-of: kk-example
spec:
  replicas: 1
  selector:
    matchLabels:
      application: agnhost
  template:
    metadata:
      labels:
        application: agnhost
      annotations:
        co.elastic.monitor/0.type: icmp
        co.elastic.monitor/0.hosts: ${data.host}
        co.elastic.monitor/0.schedule: "@every 5s"
        co.elastic.monitor/0.name: ${data.kubernetes.pod.name}
        co.elastic.monitor/0.tags.0: agnhost
        co.elastic.monitor/0.tags.1: development
        co.elastic.monitor/0.tags.2: pod
        co.elastic.monitor/1.type: tcp
        co.elastic.monitor/1.hosts: ${data.host}:8080
        co.elastic.monitor/1.schedule: "@every 5s"
        co.elastic.monitor/1.name: ${data.kubernetes.pod.name}
        co.elastic.monitor/1.tags.0: agnhost
        co.elastic.monitor/1.tags.1: development
        co.elastic.monitor/1.tags.2: pod
        co.elastic.monitor/2.type: http
        co.elastic.monitor/2.hosts: ${data.host}:8080/
        co.elastic.monitor/2.schedule: "@every 5s"
        co.elastic.monitor/2.name: ${data.kubernetes.pod.name}
        co.elastic.monitor/2.tags.0: agnhost
        co.elastic.monitor/2.tags.1: development
        co.elastic.monitor/2.tags.2: pod
    spec:
      volumes:
        - name: config
          configMap:
            defaultMode: 0777
            name:  agnhost
      initContainers:
        - name: ngnixconfig
          image: alpine/curl:3.14
          imagePullPolicy: Always
          env:
            - name: NGCONF_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ["/bin/sh"]
          args: 
            - -c
            - >-
              echo "{\"data\": {\"agnhost\": \"$(cat /tmp/service.conf |sed 's/$/\\n/g')\"}}" > /tmp/patch.json;
              curl -skX PATCH https://kubernetes.default.svc/api/v1/namespaces/$NGCONF_NAMESPACE/configmaps/openresty -H "Authorization: Bearer $( cat /var/run/secrets/kubernetes.io/serviceaccount/token )" -H "Content-Type: application/merge-patch+json; charset=utf-8" -d "@/tmp/patch.json"
          volumeMounts:
            - name: config
              mountPath: /tmp/service.conf
              readOnly: true
              subPath: service.conf
      containers:
        - name: agnhost
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          imagePullPolicy: IfNotPresent
          command:
            - /agnhost
            - netexec
            - --http-port
            - "8080"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
             requests:
               memory: 10Mi
               cpu: 10m
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst