cluster:
  workers: 3
  name: mycluster
  bootstrap:
    nginx:
      enabled: yes
      apply:
        started: 2023-07-07_19:33:57
        validated: 2023-07-07_19:33:58
        finished: 2023-07-07_19:34:50
    argocd:
      enabled: yes
      apply:
        started: 2023-07-07_19:33:59
        validated: 2023-07-07_19:33:59
        finished: 2023-07-07_19:34:50
      namespace: argocd
      password: Password123
      domain: rec.la
      tls_folder: /tmp
  plan:
    validated: 2023-07-07_19:33:57
    approved: 2023-07-07_19:33:57
  apply:
    started: 2023-07-07_19:33:57
    validated: 2023-07-07_19:33:57