---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  agnhost
  labels:
    app:  agnhost
  annotations:
    reloader.stakater.com/match: "true"
data:
  service.conf: |-
    location /agnhost {
        proxy_pass http://agnhost:8080;
        include /usr/local/openresty/nginx/conf/proxy.conf;
    }

---
kind: Service
apiVersion: v1
metadata:
  name: agnhost
spec:
  selector:
    app: agnhost
  ports:
  - port: 8080
  
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: agnhost
  labels:
    deployment: agnhost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agnhost
      deployment: agnhost
  template:
    metadata:
      labels:
        app: agnhost
        deployment: agnhost
    spec:
      volumes:
        - name: config
          configMap:
            defaultMode: 0777
            name:  agnhost
      initContainers:
        - name: ngnixconfig
          image: alpine/curl:3.14
          imagePullPolicy: Always
          env:
            - name: NGCONF_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ["/bin/sh"]
          args: 
            - -c
            - >-
              echo "{\"data\": {\"agnhost\": \"$(cat /tmp/service.conf |sed 's/$/\\n/g')\"}}" > /tmp/patch.json;
              curl -skX PATCH https://kubernetes.default.svc/api/v1/namespaces/$NGCONF_NAMESPACE/configmaps/openresty -H "Authorization: Bearer $( cat /var/run/secrets/kubernetes.io/serviceaccount/token )" -H "Content-Type: application/merge-patch+json; charset=utf-8" -d "@/tmp/patch.json"
          volumeMounts:
            - name: config
              mountPath: /tmp/service.conf
              readOnly: true
              subPath: service.conf
      containers:
        - name: agnhost
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          imagePullPolicy: IfNotPresent
          command:
            - /agnhost
            - netexec
            - --http-port
            - "8080"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
             requests:
               memory: 10Mi
               cpu: 10m
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

