---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
  labels:
    application: filebeat
    version: "7.17.11"
    release: "r7"
    stage: development
    component: elasticstack
    part-of: observabillity
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    processors:
      - add_host_metadata: ~

    output.elasticsearch:
      hosts: ['${ELASTIC_CUSTOM_HOST:elasticsearch}:${ELASTIC_CUSTOM_PORT:9200}']
      username: ${ELASTIC_CUSTOM_USERNAME:elastic}
      # password: ${ELASTIC_PASSWORD}