---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  hello
  labels:
    app:  hello
  annotations:
    reloader.stakater.com/match: "true"
data:
  service.conf: |-
    location /hello {
        proxy_pass http://hello:5678;
        include /usr/local/openresty/nginx/conf/proxy.conf;
    }

---
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
  - port: 5678
  

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
  labels:
    deployment: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      deployment: hello
  template:
    metadata:
      labels:
        app: hello
        deployment: hello
    spec:
      volumes:
        - name: config
          configMap:
            defaultMode: 0777
            name:  hello
      initContainers:
        - name: ngnixconfig
          image: alpine/curl:3.14
          imagePullPolicy: Always
          env:
            - name: NGCONF_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ["/bin/sh"]
          args: 
            - -c
            - >-
              echo "{\"data\": {\"hello\": \"$(cat /tmp/service.conf |sed 's/$/\\n/g')\"}}" > /tmp/patch.json;
              curl -skX PATCH https://kubernetes.default.svc/api/v1/namespaces/$NGCONF_NAMESPACE/configmaps/openresty -H "Authorization: Bearer $( cat /var/run/secrets/kubernetes.io/serviceaccount/token )" -H "Content-Type: application/merge-patch+json; charset=utf-8" -d "@/tmp/patch.json"
          volumeMounts:
            - name: config
              mountPath: /tmp/service.conf
              readOnly: true
              subPath: service.conf
      containers:
        - name: hello
          image: hashicorp/http-echo:alpine
          imagePullPolicy: IfNotPresent
          args:
            - '--text=Hello World'
          ports:
            - containerPort: 5678
              protocol: TCP
          resources:
             requests:
               memory: 10Mi
               cpu: 10m
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst